### ISSUE TITLE
Línea del tiempo de la WEB 1.0-3.0

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-7-edgarmauricio123#1]
Edgar Mauricio Sarmiento Ruiz
Grupo:1BS

![linea-del-tiempo-WEB-1 0-3 0](https://user-images.githubusercontent.com/112227375/196234855-20b55f1a-c635-4766-aa3b-8857479ca5f9.png)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 7 "LINEA DEL TIEMPO DE LA WEB"
DE ACUERDO A LA RUBRICA OBTUVISTE ("16.9%") DEL 20% QUE EQUIVALE LA ACTIVIDAD.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
